name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install flake8 mypy pytest

      - name: Run flake8
        run: flake8

      - name: Run mypy
        run: mypy test_spending_tracker_mypy.py

      - name: Run unit tests
        run: pytest test_spending_tracker_pytest.py -v